syntax = "proto3";

package namespace.v1;

import "namespace/v1/namespace.proto";

message ListNamespacesRequest {
  string catalog_name = 1;
}

message ListNamespacesResponse {
  repeated DataSourceNamespace namespaces = 1;
}

message DescribeNamespaceRequest {
  string catalog_name = 1;
  string data_source_name = 2;
  repeated string namespace_names = 3;
}

message DescribeNamespaceResponse {
  optional Namespace namespace = 1;
}

message DescribeNamespaceByIdRequest {
  string namespace_id = 1;
}

message DescribeNamespaceByIdResponse {
  optional Namespace namespace = 1;
}

service NamespaceService {
  // ListNamespaces returns a list of namespaces in the catalog.
  // The namespaces are returned together with the data sources they belong to.
  rpc ListNamespaces(ListNamespacesRequest) returns (ListNamespacesResponse) {}

  // DescribeNamespace returns a namespace by name.
  rpc DescribeNamespace(DescribeNamespaceRequest) returns (DescribeNamespaceResponse) {}

  // DescribeNamespaceById returns a namespace by ID.
  rpc DescribeNamespaceById(DescribeNamespaceByIdRequest) returns (DescribeNamespaceByIdResponse) {}
}
