syntax = "proto3";

package table.v1;

import "datasource/v1/data_source.proto";
import "namespace/v1/namespace.proto";

message TableInfo {
  string id = 1;
  string namespace_id = 2;
  string name = 3;
}

message Table {
  TableInfo info = 1;
}

message Column {
  string id = 1;
  string table_id = 2;
  string name = 3;
  string type = 4;
  int32 ordinal_position = 5;
  bool nullable = 6;
}

message TableDetail {
  TableInfo info = 1;
  repeated Column columns = 2;
}

message DataSourceNamespaceTable {
  datasource.v1.DataSource data_source = 1;
  namespace.v1.Namespace namespace = 2;
  Table table = 3;
}

message DataSourceNamespaceTableDetail {
  datasource.v1.DataSource data_source = 1;
  namespace.v1.Namespace namespace = 2;
  TableDetail table_detail = 3;
}
